name: verify
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  install:
    name: install
    runs-on: ubuntu-latest
    steps:
      # Checkout repo to Github Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      # Install Node
      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: yarn
  build:
    name: build
    needs: install
    runs-on: ubuntu-latest
    steps:
      # Checkout repo to Github Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      # Install Node
      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: yarn

      - name: Run build
        run: yarn build
  lint:
    name: lint
    needs: install
    runs-on: ubuntu-latest
    steps:
      # Checkout repo to Github Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      # Install Node
      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: yarn

      - name: Run lint
        run: yarn lint
  test:
    name: test
    needs: install
    runs-on: ubuntu-latest
    steps:
      # Checkout repo to Github Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      # Install Node
      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: yarn

      - name: Run test
        run: yarn test
